export const menPhotosConstants = {
  FETCH_MEN_PHOTOS_PENDING: 'FETCH_MEN_PHOTOS_PENDING',
  FETCH_MEN_PHOTOS_SUCCESS: 'FETCH_MEN_PHOTOS_SUCCESS',
  FETCH_MEN_PHOTOS_ERROR: 'FETCH_MEN_PHOTOS_ERROR',
};
