export const womenPhotosConstants = {
  FETCH_WOMEN_PHOTOS_PENDING: 'FETCH_WOMEN_PHOTOS_PENDING',
  FETCH_WOMEN_PHOTOS_SUCCESS: 'FETCH_WOMEN_PHOTOS_SUCCESS',
  FETCH_WOMEN_PHOTOS_ERROR: 'FETCH_WOMEN_PHOTOS_ERROR',
};
